### ISSUE TITLE
Missing script in setup instructions

### ISSUE THREAD

**Issue by johnennewgreenshootlabs** [opendialogai/opendialog-dev-environment#9]
One of the setup steps says:

> run `bash update-web-chat.sh -iy` to build the webchat widget for interacting with the bot

This step complains it can't find the script:

> root@29baadf30d1e:/var/www/opendialog# bash update-web-chat.sh -iy
bash: update-web-chat.sh: No such file or directory

I found it in the `vendor/opendialogai/webchat/resources/scripts` dir and ran it from there which seemed to work:

> root@29baadf30d1e:/var/www/opendialog# bash ./vendor/opendialogai/webchat/resources/scripts/update-web-chat.sh -iy
Running setup for dev environment
Installing node dependencies

**Comment by istos** [comment]
Good catch - thanks for that. We don't actually need to run that script anymore as assets are built already. Updated documentation to reflect that - https://github.com/opendialogai/opendialog-dev-environment/commit/3caaf03a422e8217ee5f621e0183d8b96929cc64
